version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: gui
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: electron
    schedule:
      interval: monthly
