stages:
  - test
test:
  before_script:
    - pip install -e ".[dev]"
  image: python:${PYTHON_VERSION}-slim
  parallel:
    matrix:
      - MB_FS_HOST: seaweedfs
        MB_FS_PORT: '8333'
        PYTHON_VERSION:
          - '3.10'
          - '3.14'
      - MB_FS_HOST: rustfs
        MB_FS_PORT: '9000'
        PYTHON_VERSION:
          - '3.10'
          - '3.14'
  script:
    - pytest
  services:
    - alias: mongodb
      name: mongo:latest
      pull_policy: if-not-present
      variables:
        MONGO_INITDB_DATABASE: StrongMotion
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_ROOT_USERNAME: test
    - alias: rabbitmq
      name: rabbitmq:4.2
      pull_policy: if-not-present
      variables:
        RABBITMQ_DEFAULT_PASS: password
        RABBITMQ_DEFAULT_USER: test
        RABBITMQ_DEFAULT_VHOST: vhost
    - alias: elasticsearch
      name: elasticsearch:9.3.5
      pull_policy: if-not-present
      variables:
        ES_JAVA_OPTS: '-Xms512m -Xmx512m'
        discovery.type: single-node
        xpack.security.enabled: false
    - alias: seaweedfs
      name: chrislusf/seaweedfs
      pull_policy: if-not-present
      variables:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: password
    - alias: rustfs
      name: rustfs/rustfs:latest
      pull_policy: if-not-present
      variables:
        RUSTFS_ACCESS_KEY: test
        RUSTFS_SECRET_KEY: password
  stage: test
variables:
  ELASTIC_HOST: elasticsearch
  MB_FS_HOST: ${MB_FS_HOST}
  MB_FS_PORT: ${MB_FS_PORT}
  MONGO_HOST: mongodb
  NUMBA_DISABLE_JIT: '1'
  RABBITMQ_HOST: rabbitmq
