[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only"
]
dependencies = [
    "aiohttp[speedups]",
    "bcrypt",
    "beanie",
    "celery",
    "elasticsearch[async]",
    "email-validator",
    "fastapi",
    "joserfc",
    "numba",
    "Pint",
    "pyinstrument",
    "python-dotenv",
    "python-multipart",
    "s3fs",
    "scipy",
    "structlog",
    "universal_pathlib",
    "uvicorn[standard]"
]
description = "a strong motion database"
dynamic = ["version"]
keywords = [
    "earthquake",
    "ground motion",
    "response history analysis",
    "strong motion",
    "seismology"
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
name = "motion-base"
readme = "README.md"
requires-python = ">=3.11"

[[project.authors]]
name = "Theodore Chang"
email = "tlcfem@gmail.com"

[[project.maintainers]]
name = "Theodore Chang"
email = "tlcfem@gmail.com"

[project.optional-dependencies]
client = ["beautifulsoup4", "click", "httpx2", "matplotlib", "rich"]
dev = ["httpx2", "locust", "pytest-cov", "ruff"]

[project.urls]
"Bug Reports" = "https://github.com/TLCFEM/motion-base/issuess"
Homepage = "https://github.com/TLCFEM/motion-base"
Source = "https://github.com/TLCFEM/motion-base"

[tool.pyright]
venv = ".venv"
venvPath = "."

[tool.pytest.ini_options]
anyio_mode = "auto"

[tool.ruff.lint]
ignore = ["B008", "E501"]
select = ["E", "F", "UP", "B", "SIM", "I"]
