version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: 'no'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: StrongMotion
      MONGO_DATA_DIR: /data/db
      volumes:
        motion_mongo:/data/db
  motion-base-back:
    image: motion-base-back
    container_name: motion-base-back
    restart: 'no'
    depends_on:
      - mongo
    ports:
      - '8000:8000'
  motion-base-front:
    image: motion-base-front
    container_name: motion-base-front
    restart: 'no'
    depends_on:
      - mongo
    ports:
      - '3000:3000'

volumes:
  motion_mongo:
