services:
  mongo:
    image: mongo
    container_name: mongo
    restart: 'no'
    command: --wiredTigerCacheSizeGB 2
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: StrongMotion
      MONGO_DATA_DIR: /data/db
    volumes:
      - motion_mongo:/data/db
      - motion_mongoconfig:/data/configdb
  motion-base-back:
    image: motion-base-back
    container_name: motion-base-back
    restart: 'no'
    depends_on:
      - mongo
    ports:
      - '8000:8000'
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SUPERUSER_USERNAME: ${SUPERUSER_USERNAME}
      SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
      SUPERUSER_FIRST_NAME: ${SUPERUSER_FIRST_NAME}
      SUPERUSER_LAST_NAME: ${SUPERUSER_LAST_NAME}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      WORKERS: 1
  motion-base-front:
    image: motion-base-front
    container_name: motion-base-front
    restart: 'no'
    depends_on:
      - motion-base-back
    ports:
      - '4173:4173'

volumes:
  motion_mongo:
  motion_mongoconfig:
