services:
  def-flower:
    command: >-
      celery
      --broker=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@dev-rabbitmq:${RABBITMQ_PORT}/vhost
      flower
      --broker_api=http://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@dev-rabbitmq:15672/api/vhost
    container_name: dev-flower
    image: mher/flower
    ports:
      - '5555:5555'
    restart: 'no'
    volumes:
      - flower:/data
  dev-elasticsearch:
    container_name: dev-elasticsearch
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx1g'
      discovery.type: single-node
      xpack.security.enabled: false
    healthcheck:
      interval: 300s
      retries: 5
      start_period: 10s
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:9200/_cluster/health
      timeout: 10s
    image: elasticsearch:${ELASTIC_VERSION}
    ports:
      - '9200:9200'
    restart: 'no'
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  dev-mongo:
    command: '--wiredTigerCacheSizeGB ${MONGO_CACHE_SIZE} --port ${MONGO_PORT}'
    container_name: dev-mongo
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    healthcheck:
      interval: 300s
      retries: 5
      start_period: 10s
      test:
        - CMD
        - mongosh
        - '--eval'
        - db.adminCommand('ping')
        - '--quiet'
      timeout: 10s
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: 'no'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
  dev-mongo-express:
    container_name: dev-mongo-express
    environment:
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@dev-mongo:${MONGO_PORT}/
    image: mongo-express
    ports:
      - '8081:8081'
    restart: 'no'
  dev-rabbitmq:
    container_name: dev-rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_NODE_PORT: ${RABBITMQ_PORT}
    healthcheck:
      interval: 300s
      retries: 5
      start_period: 10s
      test:
        - CMD
        - rabbitmq-diagnostics
        - '-q'
        - ping
      timeout: 10s
    image: rabbitmq:4.2-management
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    restart: 'no'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  dev-seaweedfs:
    container_name: dev-seaweedfs
    environment:
      AWS_ACCESS_KEY_ID: ${MB_FS_USERNAME}
      AWS_SECRET_ACCESS_KEY: ${MB_FS_PASSWORD}
    image: chrislusf/seaweedfs
    ports:
      - '8333:8333'
    restart: 'no'
    volumes:
      - seaweedfs_data:/data
volumes:
  elasticsearch: null
  flower: null
  mongo_config: null
  mongo_data: null
  rabbitmq: null
  seaweedfs_data: null
