version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: 'no'
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: StrongMotion
      MONGO_DATA_DIR: /data/db
      volumes:
        motion_mongo:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: 'no'
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://test:password@mongo:27017/
  motion-base:
    image: motion-base
    container_name: motion-base
    restart: 'no'
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    links:
      - mongo

volumes:
  motion_mongo:
