services:
  dev-mongo:
    image: mongo
    container_name: dev-mongo
    restart: 'no'
    command: --wiredTigerCacheSizeGB 2 --port ${MONGO_PORT}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: StrongMotion
      MONGO_DATA_DIR: /data/db
    volumes:
      - motion_mongo:/data/db
      - motion_mongoconfig:/data/configdb
  dev-mongo-express:
    image: mongo-express
    container_name: dev-mongo-express
    restart: 'no'
    depends_on:
      - dev-mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@dev-mongo:${MONGO_PORT}/
  dev-rabbitmq:
    image: rabbitmq
    container_name: dev-rabbitmq
    restart: 'no'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: vhost

volumes:
  motion_mongo:
  motion_mongoconfig:
