services:
  mongo:
    image: mongo
    container_name: mongo
    restart: 'always'
    command: --wiredTigerCacheSizeGB 2 --port ${MONGO_PORT}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: StrongMotion
      MONGO_DATA_DIR: /data/db
    volumes:
      - motion_mongo:/data/db
      - motion_mongoconfig:/data/configdb
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: 'always'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: vhost
  mb-back:
    image: tlcfem/motion-base-back
    container_name: mb-back
    restart: 'always'
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - '${MB_PORT}:${MB_PORT}'
    volumes:
      - motion_cache:${MB_FS_ROOT}
    environment:
      MB_SECRET_KEY: ${MB_SECRET_KEY}
      MB_ALGORITHM: ${MB_ALGORITHM}
      MB_ACCESS_TOKEN_EXPIRE_MINUTES: ${MB_ACCESS_TOKEN_EXPIRE_MINUTES}
      MB_SUPERUSER_EMAIL: ${MB_SUPERUSER_EMAIL}
      MB_SUPERUSER_FIRST_NAME: ${MB_SUPERUSER_FIRST_NAME}
      MB_SUPERUSER_LAST_NAME: ${MB_SUPERUSER_LAST_NAME}
      MB_SUPERUSER_USERNAME: ${MB_SUPERUSER_USERNAME}
      MB_SUPERUSER_PASSWORD: ${MB_SUPERUSER_PASSWORD}
      MB_PORT: ${MB_PORT}
      MB_FASTAPI_WORKERS: 2
      MB_FS_ROOT: ${MB_FS_ROOT}
      MB_MAIN_SITE: ${MB_MAIN_SITE}
      MB_CELERY: ${MB_CELERY}
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
  mb-worker:
    image: tlcfem/motion-base-back
    container_name: mb-worker
    restart: 'always'
    depends_on:
      - mongo
      - rabbitmq
    command: celery
    volumes:
      - motion_cache:${MB_FS_ROOT}
    environment:
      MB_SECRET_KEY: ${MB_SECRET_KEY}
      MB_ALGORITHM: ${MB_ALGORITHM}
      MB_ACCESS_TOKEN_EXPIRE_MINUTES: ${MB_ACCESS_TOKEN_EXPIRE_MINUTES}
      MB_SUPERUSER_EMAIL: ${MB_SUPERUSER_EMAIL}
      MB_SUPERUSER_FIRST_NAME: ${MB_SUPERUSER_FIRST_NAME}
      MB_SUPERUSER_LAST_NAME: ${MB_SUPERUSER_LAST_NAME}
      MB_SUPERUSER_USERNAME: ${MB_SUPERUSER_USERNAME}
      MB_SUPERUSER_PASSWORD: ${MB_SUPERUSER_PASSWORD}
      MB_PORT: ${MB_PORT}
      MB_FASTAPI_WORKERS: 2
      MB_FS_ROOT: ${MB_FS_ROOT}
      MB_MAIN_SITE: ${MB_MAIN_SITE}
      MB_CELERY: ${MB_CELERY}
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
  mb-front:
    image: tlcfem/motion-base-front
    container_name: mb-front
    restart: 'always'
    depends_on:
      - mb-back
    ports:
      - '4173:4173'

volumes:
  motion_mongo:
  motion_mongoconfig:
  motion_cache:
