services:
  dev-mongo:
    image: mongo
    container_name: dev-mongo
    restart: no
    command: --wiredTigerCacheSizeGB ${MONGO_CACHE_SIZE} --port ${MONGO_PORT}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATA_DIR: /data/db
    volumes:
      - motion_mongo:/data/db
      - motion_mongoconfig:/data/configdb
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 300s
      timeout: 10s
      start_period: 10s
      retries: 5
  dev-mongo-express:
    image: mongo-express
    container_name: dev-mongo-express
    restart: no
    depends_on:
      dev-mongo:
        condition: service_healthy
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@dev-mongo:${MONGO_PORT}/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
  dev-rabbitmq:
    image: rabbitmq:management
    container_name: dev-rabbitmq
    restart: no
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
    environment:
      RABBITMQ_NODE_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - motion_rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 300s
      timeout: 10s
      start_period: 10s
      retries: 5
  def-flower:
    image: mher/flower
    container_name: dev-flower
    restart: no
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: celery --broker=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@dev-rabbitmq:${RABBITMQ_PORT}/vhost flower --broker_api=http://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@dev-rabbitmq:15672/api/vhost
    ports:
      - '5555:5555'
    volumes:
      - motion_flower:/data
  dev-elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: dev-elasticsearch
    restart: no
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx1g"
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - motion_elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 300s
      timeout: 10s
      start_period: 10s
      retries: 5

volumes:
  motion_mongo:
  motion_mongoconfig:
  motion_rabbitmq:
  motion_flower:
  motion_elasticsearch:
