apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-storage
  labels:
    app: mb-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mb-storage
  template:
    metadata:
      name: mb-storage
      labels:
        app: mb-storage
    spec:
      volumes:
        - name: motion-rabbitmq
          emptyDir: {}
        - name: motion-elasticsearch
          emptyDir: {}
        - name: motion-mongo
          emptyDir: {}
        - name: motion-mongoconfig
          emptyDir: {}
      containers:
        - name: mb-rabbitmq
          image: rabbitmq
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: motion-rabbitmq
              mountPath: /var/lib/rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: mb-config
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: mb-config
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_DEFAULT_VHOST
              value: vhost
            - name: RABBITMQ_NODE_PORT
              value: "5672"
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
              cpu: "0.5"
        - name: mb-elasticsearch
          image: elasticsearch:9.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - name: motion-elasticsearch
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "4Gi"
              cpu: "0.5"
        - name: mb-mongo
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: motion-mongo
              mountPath: /data/db
            - name: motion-mongoconfig
              mountPath: /data/configdb
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mb-config
                  key: MONGO_DB_NAME
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mb-config
                  key: MONGO_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mb-config
                  key: MONGO_PASSWORD
            - name: MONGO_DATA_DIR
              value: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "4Gi"
              cpu: "1"
      restartPolicy: Always
