jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Deployment
        uses: strumwolf/delete-deployment-environment@v4
        with:
          environment: github-pages
          token: ${{ secrets.ALL }}
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6
        with:
          owner_type: user
          package_name: motion-base
          token: ${{ secrets.ALL }}
          untagged_only: true
name: Delete
'on':
  workflow_dispatch: null
