name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Dependency
        run: |
          pip install --upgrade pip
          pip install -e .[dev]
      - name: MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-username: test
          mongodb-password: password
          mongodb-db: StrongMotion
      - name: Lint
        run: |
          pylint src
      - name: Test
        run: |
          pytest --cov .
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TLCFEM/motion-base
          plugin: pycoverage
  docker:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: back.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/motion-base-back:latest
      - name: Build Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: front.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/motion-base-front:latest
