name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-username: test
          mongodb-password: password
          mongodb-db: StrongMotion
      - name: Lint
        run: |
          pylint mb
      - name: Test
        run: |
          pytest --cov .
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
