name: Release
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: StrongMotion
        ports:
          - "27017:27017"
      rabbitmq:
        image: rabbitmq:latest
        env:
          RABBITMQ_DEFAULT_USER: test
          RABBITMQ_DEFAULT_PASS: password
          RABBITMQ_DEFAULT_VHOST: vhost
        ports:
          - "5672:5672"
      elasticsearch:
        image: elasticsearch:9.1.0
        ports:
          - "9200:9200"
        env:
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          discovery.type: single-node
          xpack.security.enabled: false
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Dependency
        run: |
          pip install --upgrade pip
          pip install uv
          uv pip install --system -e .[dev] pyinstaller
          export NUMBA_DISABLE_JIT=1
          pytest -n auto --cov --junitxml=junit.xml .
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TLCFEM/motion-base
          plugins: pycoverage
      - name: Result
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Binary
        if: matrix.python-version == '3.11'
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          /bin/bash ./scripts/pyinstaller.sh
      - name: Artifact
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
      - name: Release
        id: release
        if: github.event_name == 'push' && matrix.python-version == '3.11'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: latest
          overwrite: true
          body: |
            The binaries are standalone executables that can be run on Linux.

            1. `mb_runner`: The main application that can run the server, or the celery worker.
            2. `nied_crawler`: A specialized tool to crawl and download data from the NIED website.
            3. `nzsm_crawler`: A specialized tool to crawl and download data from the NZ Strong Motion database.
      - name: VirusTotal
        if: steps.release.outputs.release_id
        uses: TLCFEM/virustotal-action@feature-explicit-release-id
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.release.outputs.release_id }}
  docker:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: Clone
        uses: actions/checkout@v5
      - name: Update
        run: /bin/bash ./scripts/git-commit.sh
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: back.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tlcfem/motion-base:back
            ghcr.io/tlcfem/motion-base:back
      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: front.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tlcfem/motion-base:front
            ghcr.io/tlcfem/motion-base:front
