concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        env:
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
          discovery.type: single-node
          xpack.security.enabled: false
        image: elasticsearch:9.3.5
        ports:
          - '9200:9200'
      mongodb:
        env:
          MONGO_INITDB_DATABASE: StrongMotion
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_ROOT_USERNAME: test
        image: mongo:latest
        ports:
          - '27017:27017'
      rabbitmq:
        env:
          RABBITMQ_DEFAULT_PASS: password
          RABBITMQ_DEFAULT_USER: test
          RABBITMQ_DEFAULT_VHOST: vhost
        image: rabbitmq:4.2-management
        ports:
          - '5672:5672'
      rustfs:
        env:
          RUSTFS_ACCESS_KEY: test
          RUSTFS_SECRET_KEY: password
        image: rustfs/rustfs:latest
        ports:
          - '9000:9000'
      seaweedfs:
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: password
        image: chrislusf/seaweedfs
        ports:
          - '8333:8333'
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dependency
        run: |
          pip install -e .[dev] pyinstaller
          export NUMBA_DISABLE_JIT=1
          ruff check
          pytest --cov --junitxml=junit.xml .
      - name: Codecov
        uses: codecov/codecov-action@v6
        with:
          plugins: pycoverage
          token: ${{ secrets.CODECOV_TOKEN }}
      - if: matrix.python-version == '3.11'
        name: Binary
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          /bin/bash ./scripts/pyinstaller.sh
      - if: matrix.python-version == '3.11'
        name: Artifact
        uses: actions/upload-artifact@v7
        with:
          path: dist/*
      - id: release
        if: github.event_name == 'push' && matrix.python-version == '3.11'
        name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          body: |
            The binaries are standalone executables that can be run on Linux.

            1. `mb_runner`: The main application that can run the server, or the celery worker.
            2. `nied_crawler`: A specialized tool to crawl and download data from the NIED website.
            3. `nzsm_crawler`: A specialized tool to crawl and download data from the NZ Strong Motion database.
          file: dist/*
          file_glob: true
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
      - if: steps.release.outputs.release_id
        name: VirusTotal
        uses: cssnr/virustotal-action@v2
        with:
          release_heading: '### 🛡️ VirusTotal Results'
          release_id: latest
          vt_api_key: ${{ secrets.VIRUSTOTAL_KEY }}
    strategy:
      matrix:
        python-version:
          - '3.11'
          - '3.14'
    timeout-minutes: 30
  docker:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Update
        run: /bin/bash ./scripts/git-commit.sh
      - name: Login
        uses: docker/login-action@v4
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Login GitHub
        uses: docker/login-action@v4
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: QEMU
        uses: docker/setup-qemu-action@v4
      - name: Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.image }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tlcfem/motion-base:${{ matrix.image }}
            ghcr.io/tlcfem/motion-base:${{ matrix.image }}
    strategy:
      matrix:
        image:
          - front
          - back
          - crawler
    timeout-minutes: 20
name: Release
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
